# fly.toml
app = "peeragogybot" # Changed from peeragogychatbot based on logs? Verify app name.
primary_region = "maa"

# Ensure this section is EMPTY or REMOVED if using Dockerfile
[build]

[env]
  PORT = "3000"
  HOST = "0.0.0.0"        # Standard variable (seems ignored by Flowise)
  FLOWISE_HOST = "0.0.0.0" # Flowise-specific variable (let's try this)

# Use [[services]] syntax (Recommended)
[[services]]
  protocol = "tcp"
  internal_port = 3000 # Must match PORT env var
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  # Optional but recommended health check
  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    port = "3000" # Check the internal port Flowise listens on
