# fly.toml
app = "peeragogychatbot"
primary_region = "maa"

[build]
  # Use the official Flowise image from Docker Hub
  image = "flowiseai/flowise:latest"

[env]
  # Port Flowise should listen on INSIDE the container
  PORT = "3000"
  # Tell Flowise to listen on all interfaces INSIDE the container
  HOST = "0.0.0.0" # <-- ADD THIS LINE

[http_service]
  internal_port = 3000 # Must match PORT env var
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
