app = "peeragogybot"
primary_region = "fra"

[processes]
app = "flowise start --port 3000 --host 0.0.0.0"

[env]
PORT = "3000"
HOST = "0.0.0.0"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024

