# fly.toml
app = "peeragogybot"
primary_region = "fra"

[build]

[env]
  PORT = "3000"
  # HOST and FLOWISE_HOST are likely not needed if Flowise defaults correctly,
  # but keeping them doesn't hurt.
  HOST = "0.0.0.0"
  FLOWISE_HOST = "0.0.0.0"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    port = "3000"
    grace_period = "15s" # <-- ADD THIS LINE (adjust value if needed)
